spring:
  application:
    name: CatApp2
  boot:
    admin:
      client:
        url: http://localhost:1414/
server:
 port: 1991

management:
  endpoints:
    web:
      exposure:
        include: '*'